### ISSUE TITLE
Multi-class classification

### ISSUE THREAD

**Issue by guoquan** [HLR/DomiKnowS#254]
This issue is to put together the discussion about supporting the multi-class classification in the framework.

**Comment by hfaghihi15** [comment]
I reopened this issue because we need to add information about the `keyword` we added to indicate multiclass or multilabel to the information here, @guoquan, @auszok do you have that data and syntax on how to write them?

**Comment by hfaghihi15** [comment]
@auszok do we have also the documentation on how to write constraints using the values in the list?
