### ISSUE TITLE
Data folder

### ISSUE THREAD

**Issue by AdmiralDarius** [HLR/DomiKnowS#296]
there is an allennlp folder in this folder @hfaghihi15 remove it if you don't need it.

also, write the documentation for the reader.py in [data](https://github.com/HLR/DomiKnowS/blob/develop_newLC/docs/Main%20Components/Data.md)
it has one class named class RegrReader

**Comment by hfaghihi15** [comment]
We had the reader documentation before. I just moved it to the new place you mentioned.
